# Generated by Django 4.2.26 on 2025-12-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clipboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clipboard',
            old_name='shared_id',
            new_name='share_id',
        ),
        migrations.RenameField(
            model_name='clipboard',
            old_name='shared_password',
            new_name='share_password',
        ),
    ]
