# Generated by Django 4.2.26 on 2025-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clipboard', '0002_rename_shared_id_clipboard_share_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
